server:
  port: 8888
  servlet:
    context-path: /files-system
    
files-system:
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      autoDate: true
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: /files-system/station
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      prefix: files-system
      autoDate: true
      accessKeyId: xxx
      accessKeySecret: xxx
      bucketName: xxx
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
      secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
      prefix: files-system
      autoDate: true
      region: xxx
      bucketName: xxx
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      prefix: files-system
      autoDate: true
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: emall

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file-system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root123
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    xin.spring.files.system:  DEBUG